// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBURUn7TucPqrkUx2QWBJAd62b-lzMLbO0',
    appId: '1:180183630226:android:2e82cf41f798442eb9c14b',
    messagingSenderId: '180183630226',
    projectId: 'otoparkbul-yu',
    storageBucket: 'otoparkbul-yu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVGaC4Qr3YDWSXLBPsFxW9LDsOidYxZ5U',
    appId: '1:180183630226:ios:b0cda87c76c3988cb9c14b',
    messagingSenderId: '180183630226',
    projectId: 'otoparkbul-yu',
    storageBucket: 'otoparkbul-yu.appspot.com',
    androidClientId: '180183630226-vrmsmrp8ti8j9qbj96qmvl0df602o1uh.apps.googleusercontent.com',
    iosClientId: '180183630226-5pn9opqgmg4njr966g3ka69jo7irr0pe.apps.googleusercontent.com',
    iosBundleId: 'app.otoparkbul.vendor',
  );
}
